[package]
name = "scry-core"
version.workspace = true
edition.workspace = true

[dependencies]
rkyv = { workspace = true }
memmap2 = { workspace = true }
thiserror = { workspace = true }
regex-automata = { workspace = true }
regex-syntax = { workspace = true }
memchr = { workspace = true }
aho-corasick = { workspace = true }

[dev-dependencies]
criterion = { version = "0.8.2", default-features = false, features = ["cargo_bench_support"] }
tempfile = "3"

[[bench]]
name = "query"
harness = false
